import AddNewWorkout from "./AddNewWorkout";

export const metadata = {
  title: 'Add New Workout',
  description: 'Generated by create next app',
}

export default function AddNewWorkoutPage() {
  return <AddNewWorkout />
}