import AddNewProgram from "./AddNewProgram";

export const metadata = {
  title: 'Add New Program',
  description: 'Generated by create next app',
}

export default function AddNewProgramPage() {
  return <AddNewProgram />
}