import EditExercise from "./EditExercise";

export const metadata = {
  title: 'Edit Exercise',
  description: 'Generated by create next app',
}

export default function EditExercise() {
  return (
    <div>asdasd</div>
  )
}