import EditWorkout from "./EditWorkout";

export const metadata = {
  title: 'Edit Workout',
  description: 'Generated by create next app',
}

export default function EditWorkoutPage() {
  return <EditWorkout />
}