import { ReactNode } from "react";
import Providers from "@/utils/provider";

export const metadata = {
  title: 'Become a Coach',
  description: 'Generated by create next app',
}

export default function Layout({
  children
}) {
  return (
    <Providers>
      {children}
    </Providers>
  );
}