import Coaches from './Coaches';

export const metadata = {
  title: 'Coaches',
  description: 'Generated by create next app',
}

export default function CoachesPage() {
  return (
    <Coaches />
  );
};