import CoachDetails from './CoachDetails';

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function Coach() {
  return (
    <CoachDetails />
  );
};