import AddExerciseForm from "./AddExerciseForm";

export const metadata = {
  title: 'Add Exercise Form',
  description: 'Generated by create next app',
}

export default function AddExercise() {
  return (
    <AddExerciseForm />
  )
}