import AddNewExercise from "./AddNewExercise";

export const metadata = {
  title: 'Add New Exercise',
  description: 'Generated by create next app',
}

export default function AddExercise() {
  return (
    <AddNewExercise />
  )
}